### ISSUE TITLE
No possibility to change the user after sign in

### ISSUE THREAD

**Issue by pedrr** [msintuneappsdk/intune-app-wrapping-tool-ios#28]
We want to switch the user at the app level. Is there a king of sign out feature for wrapped apps?

**Comment by Kyle-Reis** [comment]
Hey @pedrr, for wrapped applications, there are only two ways to change the enrolled identity:
1.) A manually-integrated SDK app from the same publisher enrolls with a different account.
2.) All apps from the publisher are uninstalled. Upon installation of a wrapped LOB app, the user should be prompted for credentials again.

To implement in-app account change scenarios, apps should manually integrate the Intune SDK.

**Comment by Kyle-Reis** [comment]
Hey @pedrr, just wanted to let you know that we've added the capability for users to Sign Out/Unenroll from wrapped apps since my last comment. 

Here is how:
1.) Go to iOS Settings
2.) Scroll down to your app and select it.
3.) Select "Microsoft Intune"
4.) Enable the "Sign Out On Next Launch" toggle
5.) Launch the application
