### ISSUE TITLE
Microsoft Intune Wrapping Tool Warning for IOS

### ISSUE THREAD

**Issue by R-Anusha-Dev** [msintuneappsdk/intune-app-wrapping-tool-ios#33]
Recently, i have observed the below warnings while performing Wrapping with Intune Wrapper tool for iOS Apps through a Mac OS Terminal.
****WARNING:**** 
Providing a **SHA-1 certificate** hash is **deprecated** and will not be supported in a future release. **Using a certificate name is recommended**.

****Query**:**Please provide **detail usage** for SHA1 Deprication. how to use a **certificate instead of SHA1**?

 **CRLStyle is set to 'None'**. Please set this to **'BestAttempt'** by running the command 'defaults write com.apple.security.revocation CRLStyle BestAttempt'.

**OCSPStyle is set to 'None'**. Please set this to '**BestAttempt**' by running the command 'defaults write com.apple.security.revocation OCSPStyle BestAttempt'.

****Query**:**Will it be required to update in Application code level changes or any other settings which is needed for an update?

How to avoid warnings and how to fix it?
Kindly provide the detail steps which will be helpful for me to avoid in future Applications
<img width="1036" alt="Screenshot 2019-11-06 at 12 25 49 PM" src="https://user-images.githubusercontent.com/56796501/68275026-96972580-0090-11ea-912d-fdcb618582e4.png">
.

**Comment by Kyle-Reis** [comment]
Hey @R-Anusha-Dev, The CRLStyle/OCSPStyle warnings can be addressed by simply running the commands specified in the terminal before wrapping. This only needs to be done once and you shouldn't see these warnings again when wrapping any app on the same machine.

The certificate name warning can be addressed by simply copying the "Common Name" of the certificate in the Keychain Access app instead of the SHA-1 fingerprint (under Subject Name in the certificate details). However, we've made the decision to continue support for SHA-1 hash in light of issue #30, so you should not see this warning in future updates.
