### ISSUE TITLE
There are more extensions than specified provisioning profiles. Each extension must have a corresponding provisioning profile, or a wildcard profile must be specified.

### ISSUE THREAD

**Issue by varunmehtaxebia** [msintuneappsdk/intune-app-wrapping-tool-ios#36]
Hi All,

I'm trying to Intunes wrap my .ipa having 3 extension:
**One** Service Extension for Push Notification.
**Two** Content Extension for Custom Push Notification UI

Trying to wrap the .ipa file using below steps:
1. `declare -a extension=(Desktop/Extension1.mobileprovision Desktop/Extension2.mobileprovision Desktop/Extension3.mobileprovision);`

2.  `/Volumes/IntuneMAMPackager/Contents/MacOS/IntuneMAMPackager -i Desktop/my_build.ipa -o Desktop/my_intunes_wrappped.ipa -p Desktop/MainApp.mobileprovision -x ${extension[*]} -c "EE 21 34 24 65 87 9A 65 SD 74 D2 B1 78 20 0E B2 09 3B AF 37" -v true`

**Getting below Error:**
"There are more extensions than specified provisioning profiles. Each extension must have a corresponding provisioning profile, or a wildcard profile must be specified."

**Environment Detail:**
Intunes Wrapping Tool Version: 12.2.0
Version of MACOSX is 10.14.6
Version of XCode installed is Xcode 11.3

**Comment by varunmehtaxebia** [comment]
Its working by somehow now using .plist. So closing this issue.

**Comment by ryanliljestrom** [comment]
Adding a comment here in case anybody else runs into this issue since it's not clear in the documentation: If you didn't want to use a .plist file, you need to modify the `-x` flag usage. So instead of `-x "/path/to/extension1.mobileprovision /path/to/extension2.mobileprovision"` you have to do `-x "<array><string>/path/to/extension1.mobileprovision</string><string>/path/to/extension2.mobileprovision</string></array>"`
