### ISSUE TITLE
RTL layout is not supported

### ISSUE THREAD

**Issue by almohammad** [msintuneappsdk/intune-app-wrapping-tool-ios#54]
**Describe the bug:**
After wrapping the IPA file which has Arabic default layout (Right to Left) .

**To Reproduce**
1. Double Click on MIA.dmg
2. Execute the command to wrapper the package
3. The layout is correct (RTL) Before wrapping the ipa but after wrapping file and test it again on the mobile the layout back to LTR

**Expected behavior:**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneX]
 - OS: [e.g. iOS14.4.1]

**Intune app wrapping tool (please complete the following information):**
- What version of the wrapper are you using? Are you using the latest version? Yes
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Swift
- For pre-wrapping errors, does the app build without being wrapped? Yes working fine before wrraped
- For post-wrapping errors, does the app launch without being wrapped? Yes 
- Who is the customer? Prime Minister's Office
- Do you see a trend with it only being reproduced on a specific device? Yes

**Comment by Kyle-Reis** [comment]
Hi @almohammad, are you able to share screenshots of the UI before and after wrapping?

**Comment by almohammad** [comment]
![Injaz App](https://user-images.githubusercontent.com/17505396/113854430-ed39ef00-97af-11eb-8208-39c85f91995e.jpg)

Thanks Kyl-Reis for your response , please find the attached screenshot taken from the setting of the app, kindly notice this setting is not existing when we install the IPA on the device before wrapping it so the setting back again to English after wrapping it .

How can change the default language from Intune MAM packager?

Thanks,

**Comment by Kyle-Reis** [comment]
Hi @almohammad - I have 2 questions:

1.) Is testing of the wrapped and unwrapped app being performed on the same device? Or different devices?

2.) Does the unwrapped application support localizing to multiple languages? Or is only Arabic supported?

**Comment by almohammad** [comment]
On Wed, 7 Apr 2021 at 6:54 PM Kyle Reis ***@***.***> wrote:

> Hi @almohammad <https://github.com/almohammad> - I have 2 questions:
>
> 1.) Is testing of the wrapped and unwrapped app being performed on the
> same device? Or different devices?
>
Yes performed on same device.

2.) Does the unwrapped application support localizing to multiple
> languages? Or is only Arabic supported?
>
The unwrapped application has Ar by default and yes support to localizing
multiple languages.

Thanks

**Comment by Kyle-Reis** [comment]
Thanks @almohammad. On iOS 13 and higher, the per-app "Preferred Language" setting will appear if the user has added multiple system languages in the iOS general system settings (General -> Language -> Preferred Language Order). The primary system language. Based on the screenshot you shared, it looks like the primary language on the device is English? If the primary language on the device is Arabic, this setting should default to Arabic. Also, if there is only one system language specified, this setting will not appear.

I'm not sure why the setting does not appear on the same device when the app is unwrapped if the app supports multiple languages. Does the app use custom in-app localization settings rather than built-in iOS localization via .strings files?

Note: Arabic is not  currently a supported language of the Intune SDK, so any UI shown by the Intune SDK will not localize to Arabic, even if the primary system language is Arabic, but the app's UI should remain unchanged.
